from __future__ import annotations

from fastapi import FastAPI

app = FastAPI(
    title="{{project_name}}",
    description="Web API generated by pinit.",
    version="0.1.0",
)


@app.get("/")
def root() -> dict[str, str]:
    return {"message": "Hello from {{project_name}}!"}


@app.get("/healthz")
def healthz() -> dict[str, str]:
    return {"status": "ok"}