use clap::Parser;

#[derive(Parser, Debug)]
#[command(name = "{{project_name}}")]
#[command(about = "A Rust CLI generated by pinit.")]
struct Args {
    #[arg(short, long, default_value = "World")]
    name: String,
}

fn main() {
    let args = Args::parse();
    println!("Hello {} from {{project_name}}!", args.name);
}

#[cfg(test)]
mod tests {
    #[test]
    fn it_works() {
        assert_eq!(2 + 2, 4);
    }
}
